export const teams = [
  "Elite",
  "LR Aces",
  "LR Alliance",
  "Realty Masters",
  "Solid LR",
  "Starshooters",
  "Team A",
  "Team G",
  "LR Alpha",
  "Victorious Secret",
  "Dream Team",
  "Vanguard",
  "LR Star",
  "Red Diamonds",
  "Starlight Team",
  "Wire Toppers",
  "Dreamchasers",
  "Golden Aces",
  "LR Powerhouse",
  "LR Tech Squad",
  "LR Upgrade",
  "Team Equality",
  "Team X - factor",
  "The Extreme Millionaires",
  "Team 8",
  "Infiniteam",
  "The Prodigies",
  "BEX Team Gensan",
  "Davao Eagles Direct",
  "FH VIP",
  "LR Direct",
  "LR Camsur",
  "LR Direct 2",
  "LR Patriots",
  "Team Champions",
  "Royalties",
  "Team Tycoons",
  "Luzon Leaders",
  "Luzon Ledesma",
  "FH Ozamiz",
  "FH New Force",
  "Chin Dynasty",
  "FH Racstars",
  "Filipino Homes Team 8",
  "FH Win Team",
  "G Force",
];
